### ISSUE TITLE
FYI: Generate Data?!

### ISSUE THREAD

**Issue by andretietz** [vanniktech/multiplatform-locale#201]
Hey this is more FYI, close it if not interesting for the project.

AFAIK the [flutter locale_gen library](https://github.com/impaktfull/flutter_locale_gen) is using [this project](https://github.com/countries/countries-data-json) to generate their data classes.

This might be interesting to autoupdate the Locales in the future.

**Comment by vanniktech** [comment]
Good stuff!

I found a few data points that there were missing:

- https://github.com/countries/countries/pull/875
- https://github.com/countries/countries/pull/876
- https://github.com/countries/countries/pull/877
- https://github.com/countries/countries/pull/878
- https://github.com/countries/countries/pull/879
- https://github.com/countries/countries/pull/879

Also some of our data is incorrect. Will change this right now. We're missing just 2 countries which is nice.
